### PR TITLE
multithread support

### PR DESCRIPTION
**Pull request by ksiv**
moving changes from 
https://github.com/DigitalProducts/codeception-module-visualception/commit/d408f4868d8172011d1621032d41583eea53f67f

### CODE REVIEW

**Comment by RayRom** [comment]
It shall be optionally!!! Doesn't approach.

**Comment by ksiv** [comment]
it's a fix

**Comment by buresmi7** [comment]
@ksiv: this should solve your problem, check it out: https://github.com/Codeception/VisualCeption/commit/e73cb6471cfdc1f7433b0edb6fa5a4dc94c6da80

**Comment by ksiv** [comment]
Thank you for you care and support. :-) Will check it as I m back to parallel execution. Currently pursuing scroll functionality to avoid viewpoint only screenshots. :-) I m deleting branch since you got the idea and implementation particularities doesn't matter. Let the Total Quality be with us.

**Pull request closed without merging**
