### PR TITLE
Compatibility with Codeception 2.4.0

### PR DESCRIPTION
**Pull request by eXorus**
Fix issue #39

### CODE REVIEW

**Comment by buresmi7** [comment]
Hi, thanks for fix, can you please verify, that is it works on previous version? And please change composer.json to run tests with new version

**Comment by eXorus** [comment]
Hi,

It's working with Codeception 2.3 and Codeception 2.4.

I don't understand what I need to change in compose.json.

**Comment by buresmi7** [comment]
> I don't understand what I need to change in compose.json.

To run tests with new version you need change this line: https://github.com/Codeception/VisualCeption/blob/c6718eadcffef84c831735b4a8952d81848d8314/composer.json#L11

**Comment by eXorus** [comment]
As you can see in travis
https://travis-ci.org/Codeception/VisualCeption/jobs/348272841

It's already Codeception 2.4 that are used.

**Comment by buresmi7** [comment]
you're right, sorry for my mistake, thanks!

**Comment by DavertMik** [comment]
@buresmi7 should we make a new release?

**Comment by buresmi7** [comment]
Yes, we can.

**Comment by buresmi7** [comment]
New release is now available

**Pull request merged**
